# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d038837d1cd75626eccb75106e5547e333054151ac11e921440989c02dbf766547e84b86e202be7c6762fc2eb0b43af3f85ecbfb7205b75377bfbe56367e3a4d

test:
  secret_key_base: f599d2fedcc974b867efda4e4c0b0104d7e0bb5e5fa36e0edf9e5b5ce1bb836516cb76084ff3d794bb887cbeb519bf044c6698cfa4d5047aee71785e0c310216

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
